(cl:in-package flock_msgs-msg)
(cl:export '(BATTERY_PERCENT-VAL
          BATTERY_PERCENT
          ESTIMATED_FLIGHT_TIME_REMAINING-VAL
          ESTIMATED_FLIGHT_TIME_REMAINING
          FLIGHT_MODE-VAL
          FLIGHT_MODE
          FLIGHT_TIME-VAL
          FLIGHT_TIME
          EAST_SPEED-VAL
          EAST_SPEED
          NORTH_SPEED-VAL
          NORTH_SPEED
          GROUND_SPEED-VAL
          GROUND_SPEED
          ALTITUDE-VAL
          ALTITUDE
          EQUIPMENT-VAL
          EQUIPMENT
          HIGH_TEMPERATURE-VAL
          HIGH_TEMPERATURE
          EM_GROUND-VAL
          EM_GROUND
          EM_OPEN-VAL
          EM_OPEN
          EM_SKY-VAL
          EM_SKY
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          YAW-VAL
          YAW
          AGX-VAL
          AGX
          AGY-VAL
          AGY
          AGZ-VAL
          AGZ
))