// Generated by gencpp from file svo_msgs/Info.msg
// DO NOT EDIT!


#ifndef SVO_MSGS_MESSAGE_INFO_H
#define SVO_MSGS_MESSAGE_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace svo_msgs
{
template <class ContainerAllocator>
struct Info_
{
  typedef Info_<ContainerAllocator> Type;

  Info_()
    : header()
    , processing_time(0.0)
    , keyframes()
    , num_matches(0)
    , tracking_quality(0)
    , stage(0)  {
    }
  Info_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , processing_time(0.0)
    , keyframes(_alloc)
    , num_matches(0)
    , tracking_quality(0)
    , stage(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _processing_time_type;
  _processing_time_type processing_time;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _keyframes_type;
  _keyframes_type keyframes;

   typedef int32_t _num_matches_type;
  _num_matches_type num_matches;

   typedef int32_t _tracking_quality_type;
  _tracking_quality_type tracking_quality;

   typedef int32_t _stage_type;
  _stage_type stage;





  typedef boost::shared_ptr< ::svo_msgs::Info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::svo_msgs::Info_<ContainerAllocator> const> ConstPtr;

}; // struct Info_

typedef ::svo_msgs::Info_<std::allocator<void> > Info;

typedef boost::shared_ptr< ::svo_msgs::Info > InfoPtr;
typedef boost::shared_ptr< ::svo_msgs::Info const> InfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::svo_msgs::Info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::svo_msgs::Info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace svo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'svo_msgs': ['/home/arkadiros/ROS/tello_catkin_ws/src/rpg_svo/svo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::svo_msgs::Info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::svo_msgs::Info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::svo_msgs::Info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::svo_msgs::Info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::svo_msgs::Info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::svo_msgs::Info_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::svo_msgs::Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "175acf2e539a9219addbcbeafca8552f";
  }

  static const char* value(const ::svo_msgs::Info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x175acf2e539a9219ULL;
  static const uint64_t static_value2 = 0xaddbcbeafca8552fULL;
};

template<class ContainerAllocator>
struct DataType< ::svo_msgs::Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "svo_msgs/Info";
  }

  static const char* value(const ::svo_msgs::Info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::svo_msgs::Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header      header\n\
float32     processing_time\n\
int32[]     keyframes\n\
int32       num_matches\n\
int32       tracking_quality\n\
int32       stage\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::svo_msgs::Info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::svo_msgs::Info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.processing_time);
      stream.next(m.keyframes);
      stream.next(m.num_matches);
      stream.next(m.tracking_quality);
      stream.next(m.stage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::svo_msgs::Info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::svo_msgs::Info_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "processing_time: ";
    Printer<float>::stream(s, indent + "  ", v.processing_time);
    s << indent << "keyframes[]" << std::endl;
    for (size_t i = 0; i < v.keyframes.size(); ++i)
    {
      s << indent << "  keyframes[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.keyframes[i]);
    }
    s << indent << "num_matches: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_matches);
    s << indent << "tracking_quality: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tracking_quality);
    s << indent << "stage: ";
    Printer<int32_t>::stream(s, indent + "  ", v.stage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SVO_MSGS_MESSAGE_INFO_H
